wandb_version: 1

wandb_project:
  desc: null
  value: cursivetransformer
wandb_entity:
  desc: null
  value: zwimpee
wandb_run_name:
  desc: null
  value: zachbank_v1
wandb_api_key:
  desc: null
  value: e56bbe426145e5983e72a933299daca195ebb6a7
work_dir:
  desc: null
  value: out
resume:
  desc: null
  value: false
sample_only:
  desc: null
  value: false
num_workers:
  desc: null
  value: 1
max_steps:
  desc: null
  value: 150000
lr_decay:
  desc: null
  value: 1.0
log_interval:
  desc: null
  value: 1000
eval_interval:
  desc: null
  value: 1000
sample_interval:
  desc: null
  value: 1000
device:
  desc: null
  value: cuda
seed:
  desc: null
  value: 42069
top_k:
  desc: null
  value: -1
num_words:
  desc: null
  value: 4
n_layer:
  desc: null
  value: 4
n_embd:
  desc: null
  value: 64
n_embd2:
  desc: null
  value: 64
n_head:
  desc: null
  value: 4
ablate_cross_attention:
  desc: null
  value: false
augment:
  desc: null
  value: true
max_seq_length:
  desc: null
  value: 1028
num_rotations:
  desc: null
  value: 64
num_magnitude_bins:
  desc: null
  value: 128
batch_size:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.01
weight_decay:
  desc: null
  value: 0.0001
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725048970
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.14
      5: 0.17.8
      6: ''
      8:
      - 3
      - 5
      12: ''
      13: windows-amd64
